import { QuotationData } from '../types/quotation';

export const initialFormData: QuotationData = {
  inversionType:'',
  isMsebConnection: 'Yes',
  isNameCorrection:'No',
  isEmailCorrection: 'Yes',
  isLoanRequired:'No',
  correctionType: '',
  consumerNumber: '',
  consumerName: '',
  consumerPhoneNumber: '',
  consumerEmail: '',
  consumerAddress1: '',
  consumerAddress2: '',
  connectionType: 'Residential',
  phase: 'Single',
  dcrNonDcr: 'DCR',
  batteryWattage: 0, 
  monthlyAvgUnit: 0,
  kw: 0,
  subsidy: 0,
  solarCostSystem: 0,
  fabricationCost: 0,
  effectiveCost: 0,
  pincode:NaN,
  districtCode:0,
  talukaCode:0,
  villageCode:0,
  billedTo:'',
  gstNo:''
};