import { QuotationData } from '../types/quotation';

export const initialFormData: QuotationData = {
  inversionType: '',
  isMsebConnection: 'Yes',
  isNameCorrection: 'No',
  isEmailCorrection: 'Yes',
  isOutOfStation: 'No',
  distance: 0,
  isLoanRequired: 'No',
  correctionType: '',
  consumerId: '',
  govIdName: '',
  mobileNumber: '',
  aadharNumber:'',
  panNumber:'',
  emailAddress: '',
  addressLine1: '',
  addressLine2: '',
  connectionType: 'Residential',
  phase: 'Single',
  addressType: 'Home',
  sectionId: 0,
  dcrNonDcr: 'DCR',
  batteryWattage: 0,
  monthlyAvgUnit: 0,
  latitude: '',
  longitude: '',
  kw: 0,
  acWireLengthFt: 0,
  dcWireLengthFt: 0,
  earthingWireLengthFt: 0,
  numberOfGpPipes: 0,
  descriptionOfInstallation:'',
  recommendedInstallationSpaceType:'',
  recommendedInstallationStructureType:'',
  recommendedKW:0,
  panelBrand:'',
  floorNumber: 0,
  availableSouthNorthLengthFt: 0,
  availableEastWestLengthFt: 0,
  spaceType: 'Slab',
  subsidy: 0,
  solarSystemCost: BigInt(0), // Using BigInt for accurate representation
  fabricationCost: 0,
  effectiveCost: BigInt(0), // Using BigInt for accurate representation
  pincode: '',
  districtCode: 0,
  talukaCode: 0,
  villageCode: 0,
  billedTo: '',
  gstIn: ''
};
