export const materialformDefaults = {
    //  connectionId: number,
      systemKw: "",
      makeOfModule: "",
      almmModelNo: "",
      serialNoOfModules: "",
      wattagePerModule: "",
      noOfModules: "",
      totalCapacity: "",
      warrantyDetails: "",
      inverterModuleNo: "",
      inverterMake: "",
      rating: "",
      chargeControllerType: "",
      inverterCapacity: "",
      earthingRod: "",
      dateOfInstallation: "",
      capacityType: "",
      projectModel: "",
      reInstalledCapacityRooftop: "",
      reInstalledCapacityGround: "",
      reInstalledCapacityTotal: "",
    };
    